// Jest configuration for integration tests
// Generated by Context Engineering Feature Request Decomposition System

module.exports = {
  displayName: 'Integration Tests',
  testMatch: [
    '<rootDir>/tests/integration/**/*.test.js',
    '<rootDir>/tests/integration/**/*.spec.js'
  ],
  testEnvironment: 'node',
  setupFilesAfterEnv: [
    '<rootDir>/tests/integration/setup.js'
  ],
  collectCoverageFrom: [
    'src/**/*.{js,ts}',
    '.claude/system/**/*.js',
    '!**/*.test.js',
    '!**/*.spec.js',
    '!**/node_modules/**'
  ],
  coverageDirectory: '<rootDir>/coverage/integration',
  coverageReporters: ['text', 'lcov', 'html'],
  testTimeout: 30000, // 30 seconds for integration tests
  verbose: true,
  
  // Integration test specific settings
  maxWorkers: 2, // Limit parallel execution for integration tests
  
  // Custom test environment variables
  setupFiles: [
    '<rootDir>/tests/integration/env-setup.js'
  ],
  
  // Module name mapping for integration tests
  moduleNameMapping: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@tests/(.*)$': '<rootDir>/tests/$1',
    '^@claude/(.*)$': '<rootDir>/.claude/$1'
  },
  
  // Global setup and teardown
  globalSetup: '<rootDir>/tests/integration/global-setup.js',
  globalTeardown: '<rootDir>/tests/integration/global-teardown.js',
  
  // Test result processors
  testResultsProcessor: '<rootDir>/tests/integration/results-processor.js',
  
  // Custom reporters for integration tests
  reporters: [
    'default',
    ['<rootDir>/tests/integration/integration-reporter.js', {
      outputFile: 'integration-test-results.json'
    }]
  ]
};