version: '3.8'

services:
  bmad-context:
    build: .
    container_name: bmad-context-engineering
    ports:
      - "3010:3010"
      - "3011:3011"
    volumes:
      # Mount the parent directory for multi-project access
      - ../:/workspace:rw
      # Persist SQLite database
      - ./data:/app/data:rw
      # Development volumes for hot-reload
      - ./server/src:/app/server/src:ro
      - ./client/src:/app/client/src:ro
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/data/bmad.db
      - WORKSPACE_PATH=/workspace
      - PORT=3010
      - SOCKET_CORS_ORIGIN=http://localhost:3011
    restart: unless-stopped
    networks:
      - bmad-network

networks:
  bmad-network:
    driver: bridge